### ISSUE TITLE
docs?

### ISSUE THREAD

**Issue by nilskp** [KyoriPowered/indra#28]
Any documentation or example anywhere?

**Comment by mdcfe** [comment]
See https://adventure.docs.kyori.net/index.html.

**Comment by kashike** [comment]
https://github.com/KyoriPowered/indra/wiki

**Comment by nilskp** [comment]
Yes, saw that. I want to publish to Sonatype, so I clicked through:

https://github.com/KyoriPowered/indra/wiki/indra-publishing-sonatype
